### ISSUE TITLE
Some icons were missing

### ISSUE THREAD

**Issue by amit-gshe** [zhullyb/deepin.com.dingtalk.com#1]
I just install the package from [Arch Linux AUR](https://aur.archlinux.org/packages/deepin.com.dingtalk.com/) and the app runs fine except the missing icons.  How can I help you fix it?
![截图录屏_选择区域_20200709101223](https://user-images.githubusercontent.com/7383028/86989454-097f1000-c1cd-11ea-8136-34c369a0ed85.png)

**Comment by zhullyb** [comment]
Turn on SVG support in the settings of dingtalk

**Comment by amit-gshe** [comment]
It works
