### ISSUE TITLE
能更新到deepin wine 5版本吗

### ISSUE THREAD

**Issue by GavinAndre** [zhullyb/deepin.com.dingtalk.com#2]
deepin wine 5发布了，目前使用在wechat上很完美，能否在钉钉上尝试使用下

**Comment by zhullyb** [comment]
> deepin wine 5发布了，目前使用在wechat上很完美，能否在钉钉上尝试使用下

当然可以，只不过是因为deepinwine5在别的发行版（比如Ubuntu）尚未普及，主流还是deepinwine，我并没有做出更改，你可以执行以下命令切换到deepinwine5
```
sudo sed -i "s/deepin-wine/deepin-wine5/" /opt/deepinwine/apps/Deepin-DingTalk/run.sh
```
