### ISSUE TITLE
链接可以使用默认浏览器而不是IE吗？

### ISSUE THREAD

**Issue by Jalright** [zhullyb/deepin.com.dingtalk.com#4]
链接可以使用默认浏览器而不是IE吗？
直接点击链接，就跳出了IE,哪里可以修改呢？

**Comment by zhullyb** [comment]
这个是你自己系统的环境问题，去尝试配置一下默认的html打开应用

**Comment by Jalright** [comment]
是吗？我用微信都正常

**Comment by zhullyb** [comment]
要不然你参考Arch wiki配置试试？
https://wiki.archlinux.org/index.php/Wine_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#%E5%8F%96%E6%B6%88%E6%B3%A8%E5%86%8CWine%E6%96%87%E4%BB%B6%E5%85%B3%E8%81%94
________________________________

**Comment by minbaby** [comment]
https://whoisnian.com/2017/08/14/%E8%AE%BE%E7%BD%AEWine%E8%B0%83%E7%94%A8Linux%E6%B5%8F%E8%A7%88%E5%99%A8%E4%BB%A3%E6%9B%BF%E5%86%85%E7%BD%AEIE/
网上搜了一个这个解决方案，我试了一下是可以用的，仅供参考

**Comment by Jalright** [comment]
> https://whoisnian.com/2017/08/14/%E8%AE%BE%E7%BD%AEWine%E8%B0%83%E7%94%A8Linux%E6%B5%8F%E8%A7%88%E5%99%A8%E4%BB%A3%E6%9B%BF%E5%86%85%E7%BD%AEIE/
> 网上搜了一个这个解决方案，我试了一下是可以用的，仅供参考

可以
