### ISSUE TITLE
发送图片失败

### ISSUE THREAD

**Issue by oatiz** [zhullyb/deepin.com.dingtalk.com#5]
版本：
![image](https://user-images.githubusercontent.com/24953151/97543615-71b76300-1a03-11eb-86ac-4adfcef96c88.png)

现象： （发送一直不成功，转圈圈中）
![image](https://user-images.githubusercontent.com/24953151/97543722-94e21280-1a03-11eb-9177-f7994519601c.png)

**Comment by zhullyb** [comment]
![image](https://user-images.githubusercontent.com/43305366/97784087-ef7f9800-1bd6-11eb-9137-0628011b543d.png)
你的问题恐怕无法在我这里复现

**Comment by oatiz** [comment]
发送失败后，点击重试按钮（红色小感叹号）可以发送成功。然后接下来的图片都可以发送出去
