### ISSUE TITLE
图标问题

### ISSUE THREAD

**Issue by Rvn0xsy** [zhullyb/deepin.com.dingtalk.com#6]
安装后发现钉钉左边的菜单栏和右边菜单栏按钮无法正常显示图标

![image](https://user-images.githubusercontent.com/19944759/97778043-699c2680-1baf-11eb-8fcf-9a4da83ba28e.png)

**Comment by zhullyb** [comment]
![image](https://user-images.githubusercontent.com/43305366/97783992-58b2db80-1bd6-11eb-9bf6-eee841b8a857.png)
早就写在README里面了，下次注意看
