### ISSUE TITLE
菜单图标无法显示

### ISSUE THREAD

**Issue by Rvn0xsy** [zhullyb/deepin.com.dingtalk.com#7]
![image](https://user-images.githubusercontent.com/19944759/97796320-7d956600-1c4b-11eb-8834-357fd1638b69.png)

还有左侧和右侧 ：

![image](https://user-images.githubusercontent.com/19944759/97796353-dfee6680-1c4b-11eb-94f0-71291252ac42.png)

是不是我缺少某些库导致的？

**Comment by Rvn0xsy** [comment]
而且好像输入框无法输入中文

**Comment by Rvn0xsy** [comment]
通过阅读 #3 的解答，我安装了 deepin-wine5 ：

```
sudo sed -i "s/deepin-wine/deepin-wine5/" /opt/deepinwine/apps/Deepin-DingTalk/run.sh
```

菜单图标可以显示，就是无法输入中文

**Comment by zhullyb** [comment]
在readme中，我早就提到了deepin-wine运行出现图标异常需要去设置中打开SVG支持，咱们就不能看完了再来提问嘛？
至于中文无法输入，这完全是你环境的问题

**Comment by Rvn0xsy** [comment]
关于无法输入中文的问题我解决了：
1. 确保~/.xprofile内容正常
2. 在/opt/deepinwine/apps/Deepin-DingTalk/run.sh文件开头添加如下内容：

```
export LANG=zh_CN.UTF-8
export LANGUAGE=zh_CN:en_US
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"
```

感谢
